using System;
using System.Web.UI;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Net;
using AjaxPro;
using U.Utilities.Web;

namespace UFilm.Console.AjaxServices
{
    public partial class AjaxPro_ServicesGenerateScripts : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            Utility.RegisterTypeForAjax(typeof(UFilm.Console.AjaxServices.Movies.MovieService));
            Utility.RegisterTypeForAjax(typeof(UFilm.Console.AjaxServices.SpidersService));
            Utility.RegisterTypeForAjax(typeof(UFilm.Console.AjaxServices.MoviesService));
            Utility.RegisterTypeForAjax(typeof(UFilm.Console.AjaxServices.CollectionService));
            Utility.RegisterTypeForAjax(typeof(UFilm.Console.AjaxServices.AdultsService));

            Response.Write("generate complete, please check /assets/js/ajaxservices.js");
        }


        protected override void Render(HtmlTextWriter writer)
        {
            StringWriter sw = new StringWriter();
            HtmlTextWriter html = new HtmlTextWriter(sw);
            base.Render(html);
            string pageWriteStr = sw.ToString();
            writer.Write(pageWriteStr);

            StringBuilder scripts = new StringBuilder();
            WebClient webClient = new WebClient();
            Regex reg = new Regex(@"<script type=""text/javascript"" src=""([\s\S]+?)""></script>", RegexOptions.None);
            MatchCollection matchList = reg.Matches(pageWriteStr);
            foreach (Match m in matchList)
            {
                var link = m.Groups[1].ToString();
                var url = "http://" + WebHelper.GetCurrentFullHost() + link;
                var jsBytes = webClient.DownloadData(url);
                var jsScripts = Encoding.GetEncoding("utf-8").GetString(jsBytes);
                scripts.Append(jsScripts);
            }

            //保存到文件 
            string savePath = "/assets/js/ajaxservices.js";
            var scriptContent = scripts.ToString().Replace("//--------------------------------------------------------------", "");
            scriptContent = scriptContent.Replace("// All rights reserved.", "");
            scriptContent = scriptContent.Replace("// Copyright (C) 2006 Michael Schwarz (http://www.ajaxpro.info).", "");

            File.WriteAllText(WebHelper.MapPath(savePath), "//Generated by AjaxPro_ServicesGenerateScripts：" + DateTime.Now.ToString("yyyyMMddHHmmss") + scriptContent);
        }
    }
}